### ISSUE TITLE
Unknown sign: GdbCurrentLine

### ISSUE THREAD

**Issue by lanza** [sakhnik/nvim-gdb#57]
Just rebased to check your current patch and hit this immediately. I went to the docs and copied in

          \ 'sign_current_line': '▶',
          \ 'sign_breakpoint': [ '●', '●²', '●³', '●⁴', '●⁵', '●⁶', '●⁷', '●⁸', '●⁹', '●ⁿ' ]
          \ }

to both my config and default config_override and it still errors out. Hackaround was just to `sign define GdbCurrentLine text=▶` in my init.vim.

**Comment by sakhnik** [comment]
Are you sure the Moonscript got compiled to Lua? Does running `recompile.sh` or `install.sh` change anything?

**Comment by sakhnik** [comment]
Looks like there it's gone, doesn't it?

**Comment by lanza** [comment]
Yup, it's fixed. But what caused you to rewrite the whole thing in python? 😂

**Comment by sakhnik** [comment]
I'm thinking about the other issue #53:
- We'll have easier access to the event loop to be notified when receiving socket is ready
- Less risk of crashing the whole editor if anything goes wrong (Lua was executed in the same process)
- Python is more popular, thus, may be easier for collaboration
- Python comes with the extensive library, no need for the sophisticated `install.sh`
- Python is supported by lots of development tools (like IDE, LanguageServer etc)

There are compromises though. Lua implementation seems snappier because computations happen in the same loop as GUI updates. But that isn't too much terrible.
